define(() => [
  {
    u_id: 1,
    firstName: 'Вадим',
    lastName: 'Ахмадшин',
    year: 1997,
    month: 4,
    day: 7,
    gender: 'm',
    country: '1',
    region: '1',
    city: '2',
    school: 'spbSc1',
    univer: 'spbUn1',
    friends: [2, 3, 4],
  },
  {
    u_id: 2,
    firstName: 'Anastasiya',
    lastName: 'Gaybadullina',
    year: 1998,
    month: 12,
    day: 13,
    gender: 'f',
    country: '1',
    region: '1',
    city: '3',
    school: 'ufaSc1',
    univer: 'ufaUn1',
    friends: [1, 3, 4],
  },
  {
    u_id: 3,
    firstName: 'Semen',
    lastName: 'Akhmadshin',
    year: 1996,
    month: 9,
    day: 20,
    gender: 'm',
    country: '1',
    region: '1',
    city: '2',
    school: 'spbSc2',
    univer: 'spbUn2',
    friends: [1, 2, 4],
  },
  {
    u_id: 4,
    firstName: 'Taras',
    lastName: 'Barabas',
    year: 1966,
    month: 9,
    day: 20,
    gender: 'm',
    country: '1',
    region: '1',
    city: '1',
    school: 'moscowSc1',
    univer: 'moscowUn1',
    friends: [1, 2, 3],
  },
]);
